# This notebook will clean data scraped previously and prepare for machine learning

In [299]:
import pandas as pd
import numpy as np
from pathlib import Path
from tqdm.notebook import tqdm
tqdm.pandas()

In [300]:
# Importing csv file
df_game_data = pd.read_csv(Path('original_data.csv'))
df_game_data.drop(columns='Unnamed: 0', inplace=True)
df_game_data

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22001,1610612758,SAC,Sacramento Kings,20101188,2002-04-17,SAC @ LAL,L,240,38,...,37,47,13,6,3,17,13,95,-14,0
1,22001,1610612747,LAL,Los Angeles Lakers,20101188,2002-04-17,LAL vs. SAC,W,240,44,...,35,50,22,12,2,10,23,109,14,0
2,22001,1610612762,UTA,Utah Jazz,20101184,2002-04-17,UTA vs. SAS,L,240,30,...,34,46,20,8,12,10,21,84,-2,0
3,22001,1610612743,DEN,Denver Nuggets,20101183,2002-04-17,DEN @ MIN,L,240,36,...,17,32,25,10,4,10,18,90,-14,0
4,22001,1610612739,CLE,Cleveland Cavaliers,20101178,2002-04-17,CLE @ TOR,L,240,31,...,25,36,18,5,2,19,20,85,-18,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140697,22022,1610612764,WAS,Washington Wizards,22200004,2022-10-19,WAS @ IND,W,240,42,...,39,53,21,5,10,17,19,114,7,1
140698,22022,1610612738,BOS,Boston Celtics,22200001,2022-10-18,BOS vs. PHI,W,240,46,...,30,36,24,8,3,11,24,126,9,1
140699,22022,1610612747,LAL,Los Angeles Lakers,22200002,2022-10-18,LAL @ GSW,L,240,40,...,39,48,23,12,4,22,18,109,-14,1
140700,22022,1610612744,GSW,Golden State Warriors,22200002,2022-10-18,GSW vs. LAL,W,240,45,...,37,48,31,11,4,18,23,123,14,1
140701,22022,1610612755,PHI,Philadelphia 76ers,22200001,2022-10-18,PHI @ BOS,L,240,40,...,27,31,16,8,3,14,25,117,-9,1

In [301]:
df_home_teams = df_game_data.where(df_game_data['MATCHUP'].str.contains('vs')).dropna()
df_home_teams = df_home_teams.set_index('GAME_ID')
df_home_teams

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
GAME_ID,,,,,,,,,,,,,,,,,,,,,
20101188.0,22001.0,1.610613e+09,LAL,Los Angeles Lakers,2002-04-17,LAL vs. SAC,W,240.0,44.0,101.0,...,35.0,50.0,22.0,12.0,2.0,10.0,23.0,109.0,14.0,0.0
20101184.0,22001.0,1.610613e+09,UTA,Utah Jazz,2002-04-17,UTA vs. SAS,L,240.0,30.0,83.0,...,34.0,46.0,20.0,8.0,12.0,10.0,21.0,84.0,-2.0,0.0
20101189.0,22001.0,1.610613e+09,GSW,Golden State Warriors,2002-04-17,GSW vs. LAC,W,240.0,39.0,83.0,...,38.0,47.0,25.0,11.0,10.0,14.0,25.0,107.0,4.0,0.0
20101176.0,22001.0,1.610613e+09,BOS,Boston Celtics,2002-04-17,BOS vs. ATL,W,240.0,35.0,82.0,...,36.0,49.0,25.0,8.0,7.0,20.0,19.0,89.0,8.0,0.0
20101185.0,22001.0,1.610613e+09,PHX,Phoenix Suns,2002-04-17,PHX vs. DAL,W,240.0,34.0,79.0,...,36.0,47.0,27.0,9.0,3.0,12.0,13.0,89.0,13.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22200007.0,22022.0,1.610613e+09,MIA,Miami Heat,2022-10-19,MIA vs. CHI,L,240.0,37.0,80.0,...,38.0,46.0,21.0,6.0,2.0,19.0,24.0,108.0,-8.0,1.0
22200003.0,22022.0,1.610613e+09,DET,Detroit Pistons,2022-10-19,DET vs. ORL,W,240.0,40.0,94.0,...,29.0,41.0,31.0,11.0,4.0,13.0,21.0,113.0,4.0,1.0
22200005.0,22022.0,1.610613e+09,ATL,Atlanta Hawks,2022-10-19,ATL vs. HOU,W,240.0,45.0,90.0,...,34.0,38.0,30.0,12.0,5.0,9.0,18.0,117.0,10.0,1.0
22200001.0,22022.0,1.610613e+09,BOS,Boston Celtics,2022-10-18,BOS vs. PHI,W,240.0,46.0,82.0,...,30.0,36.0,24.0,8.0,3.0,11.0,24.0,126.0,9.0,1.0
22200002.0,22022.0,1.610613e+09,GSW,Golden State Warriors,2022-10-18,GSW vs. LAL,W,240.0,45.0,99.0,...,37.0,48.0,31.0,11.0,4.0,18.0,23.0,123.0,14.0,1.0

In [302]:
df_home_teams.drop(columns=['TEAM_ABBREVIATION','TEAM_NAME', 'MATCHUP', 'VIDEO_AVAILABLE'], inplace= True)

In [303]:
df_home_teams.dtypes
df_home_teams.replace({'W': [1],
                       'L': [0]
},inplace=True)

In [304]:
df_home_teams.dtypes
df_home_teams.rename(columns={
    'TEAM_ID':'HOME_TEAM_ID',
    'WL':'HOME_TEAM_WINS',
    'MIN':'HOME_TEAM_MIN',
    'FGM':'HOME_TEAM_FGM',
    'FGA':'HOME_TEAM_FGA',
    'FG_PCT':'HOME_TEAM_FG_PCT',
    'FG3M':'HOME_TEAM_FG3M',
    'FG3A':'HOME_TEAM_FG3A',
    'FG3_PCT':'HOME_TEAM_FG3_PCT',
    'FTM':'HOME_TEAM_FTM',
    'FTA':'HOME_TEAM_FTA',
    'FT':'HOME_TEAM_FT',
    'FT_PCT':'HOME_TEAM_FT_PCT',
    'OREB':'HOME_TEAM_OREB',
    'DREB':'HOME_TEAM_DREB',
    'REB':'HOME_TEAM_REB',
    'AST':'HOME_TEAM_AST',
    'STL':'HOME_TEAM_STL',
    'BLK':'HOME_TEAM_BLK',
    'TOV':'HOME_TEAM_TOV',
    'PF':'HOME_TEAM_PF',
    'PTS':'HOME_TEAM_PTS',
    'PLUS_MINUS':'HOME_TEAM_PLUS_MINUS'
},inplace=True)

In [305]:
df_home_teams.dtypes

SEASON_ID               float64
HOME_TEAM_ID            float64
GAME_DATE                object
HOME_TEAM_WINS            int64
HOME_TEAM_MIN           float64
HOME_TEAM_FGM           float64
HOME_TEAM_FGA           float64
HOME_TEAM_FG_PCT        float64
HOME_TEAM_FG3M          float64
HOME_TEAM_FG3A          float64
HOME_TEAM_FG3_PCT       float64
HOME_TEAM_FTM           float64
HOME_TEAM_FTA           float64
HOME_TEAM_FT_PCT        float64
HOME_TEAM_OREB          float64
HOME_TEAM_DREB          float64
HOME_TEAM_REB           float64
HOME_TEAM_AST           float64
HOME_TEAM_STL           float64
HOME_TEAM_BLK           float64
HOME_TEAM_TOV           float64
HOME_TEAM_PF            float64
HOME_TEAM_PTS           float64
HOME_TEAM_PLUS_MINUS    float64
dtype: object

In [306]:
df_away_teams = df_game_data.where(df_game_data['MATCHUP'].str.contains('@')).dropna()
df_away_teams = df_away_teams.set_index('GAME_ID')
df_away_teams

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
GAME_ID,,,,,,,,,,,,,,,,,,,,,
20101188.0,22001.0,1.610613e+09,SAC,Sacramento Kings,2002-04-17,SAC @ LAL,L,240.0,38.0,84.0,...,37.0,47.0,13.0,6.0,3.0,17.0,13.0,95.0,-14.0,0.0
20101183.0,22001.0,1.610613e+09,DEN,Denver Nuggets,2002-04-17,DEN @ MIN,L,240.0,36.0,85.0,...,17.0,32.0,25.0,10.0,4.0,10.0,18.0,90.0,-14.0,0.0
20101178.0,22001.0,1.610613e+09,CLE,Cleveland Cavaliers,2002-04-17,CLE @ TOR,L,240.0,31.0,80.0,...,25.0,36.0,18.0,5.0,2.0,19.0,20.0,85.0,-18.0,0.0
20101180.0,22001.0,1.610613e+09,MIA,Miami Heat,2002-04-17,MIA @ ORL,W,240.0,45.0,85.0,...,37.0,44.0,33.0,9.0,4.0,13.0,19.0,103.0,14.0,0.0
20101186.0,22001.0,1.610613e+09,HOU,Houston Rockets,2002-04-17,HOU @ POR,L,240.0,33.0,79.0,...,30.0,42.0,19.0,5.0,6.0,15.0,17.0,79.0,-13.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22200003.0,22022.0,1.610613e+09,ORL,Orlando Magic,2022-10-19,ORL @ DET,L,240.0,42.0,86.0,...,38.0,48.0,21.0,5.0,5.0,18.0,24.0,109.0,-4.0,1.0
22200005.0,22022.0,1.610613e+09,HOU,Houston Rockets,2022-10-19,HOU @ ATL,L,240.0,42.0,98.0,...,39.0,54.0,25.0,4.0,3.0,16.0,20.0,107.0,-10.0,1.0
22200004.0,22022.0,1.610613e+09,WAS,Washington Wizards,2022-10-19,WAS @ IND,W,240.0,42.0,92.0,...,39.0,53.0,21.0,5.0,10.0,17.0,19.0,114.0,7.0,1.0
22200002.0,22022.0,1.610613e+09,LAL,Los Angeles Lakers,2022-10-18,LAL @ GSW,L,240.0,40.0,94.0,...,39.0,48.0,23.0,12.0,4.0,22.0,18.0,109.0,-14.0,1.0
22200001.0,22022.0,1.610613e+09,PHI,Philadelphia 76ers,2022-10-18,PHI @ BOS,L,240.0,40.0,80.0,...,27.0,31.0,16.0,8.0,3.0,14.0,25.0,117.0,-9.0,1.0

In [307]:
df_away_teams.drop(columns=['TEAM_ABBREVIATION','TEAM_NAME', 'MATCHUP', 'VIDEO_AVAILABLE', 'WL', 'GAME_DATE'], inplace= True)
df_away_teams.dtypes

SEASON_ID     float64
TEAM_ID       float64
MIN           float64
FGM           float64
FGA           float64
FG_PCT        float64
FG3M          float64
FG3A          float64
FG3_PCT       float64
FTM           float64
FTA           float64
FT_PCT        float64
OREB          float64
DREB          float64
REB           float64
AST           float64
STL           float64
BLK           float64
TOV           float64
PF            float64
PTS           float64
PLUS_MINUS    float64
dtype: object

In [308]:
df_away_teams.rename(columns={
    'TEAM_ID':'AWAY_TEAM_ID',
    'MIN':'AWAY_TEAM_MIN',
    'FGM':'AWAY_TEAM_FGM',
    'FGA':'AWAY_TEAM_FGA',
    'FG_PCT':'AWAY_TEAM_FG_PCT',
    'FG3M':'AWAY_TEAM_FG3M',
    'FG3A':'AWAY_TEAM_FG3A',
    'FG3_PCT':'AWAY_TEAM_FG3_PCT',
    'FTM':'AWAY_TEAM_FTM',
    'FTA':'AWAY_TEAM_FTA',
    'FT':'AWAY_TEAM_FT',
    'FT_PCT':'AWAY_TEAM_FT_PCT',
    'OREB':'AWAY_TEAM_OREB',
    'DREB':'AWAY_TEAM_DREB',
    'REB':'AWAY_TEAM_REB',
    'AST':'AWAY_TEAM_AST',
    'STL':'AWAY_TEAM_STL',
    'BLK':'AWAY_TEAM_BLK',
    'TOV':'AWAY_TEAM_TOV',
    'PF':'AWAY_TEAM_PF',
    'PTS':'AWAY_TEAM_PTS',
    'PLUS_MINUS':'AWAY_TEAM_PLUS_MINUS'
},inplace=True)

In [309]:
df_away_teams

,SEASON_ID,AWAY_TEAM_ID,AWAY_TEAM_MIN,AWAY_TEAM_FGM,AWAY_TEAM_FGA,AWAY_TEAM_FG_PCT,AWAY_TEAM_FG3M,AWAY_TEAM_FG3A,AWAY_TEAM_FG3_PCT,AWAY_TEAM_FTM,...,AWAY_TEAM_OREB,AWAY_TEAM_DREB,AWAY_TEAM_REB,AWAY_TEAM_AST,AWAY_TEAM_STL,AWAY_TEAM_BLK,AWAY_TEAM_TOV,AWAY_TEAM_PF,AWAY_TEAM_PTS,AWAY_TEAM_PLUS_MINUS
GAME_ID,,,,,,,,,,,,,,,,,,,,,
20101188.0,22001.0,1.610613e+09,240.0,38.0,84.0,0.452,5.0,18.0,0.278,14.0,...,10.0,37.0,47.0,13.0,6.0,3.0,17.0,13.0,95.0,-14.0
20101183.0,22001.0,1.610613e+09,240.0,36.0,85.0,0.424,5.0,14.0,0.357,13.0,...,15.0,17.0,32.0,25.0,10.0,4.0,10.0,18.0,90.0,-14.0
20101178.0,22001.0,1.610613e+09,240.0,31.0,80.0,0.388,7.0,17.0,0.412,16.0,...,11.0,25.0,36.0,18.0,5.0,2.0,19.0,20.0,85.0,-18.0
20101180.0,22001.0,1.610613e+09,240.0,45.0,85.0,0.529,6.0,9.0,0.667,7.0,...,7.0,37.0,44.0,33.0,9.0,4.0,13.0,19.0,103.0,14.0
20101186.0,22001.0,1.610613e+09,240.0,33.0,79.0,0.418,3.0,16.0,0.188,10.0,...,12.0,30.0,42.0,19.0,5.0,6.0,15.0,17.0,79.0,-13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22200003.0,22022.0,1.610613e+09,240.0,42.0,86.0,0.488,11.0,30.0,0.367,14.0,...,10.0,38.0,48.0,21.0,5.0,5.0,18.0,24.0,109.0,-4.0
22200005.0,22022.0,1.610613e+09,240.0,42.0,98.0,0.429,9.0,35.0,0.257,14.0,...,15.0,39.0,54.0,25.0,4.0,3.0,16.0,20.0,107.0,-10.0
22200004.0,22022.0,1.610613e+09,240.0,42.0,92.0,0.457,11.0,31.0,0.355,19.0,...,14.0,39.0,53.0,21.0,5.0,10.0,17.0,19.0,114.0,7.0
22200002.0,22022.0,1.610613e+09,240.0,40.0,94.0,0.426,10.0,40.0,0.250,19.0,...,9.0,39.0,48.0,23.0,12.0,4.0,22.0,18.0,109.0,-14.0
22200001.0,22022.0,1.610613e+09,240.0,40.0,80.0,0.500,13.0,34.0,0.382,24.0,...,4.0,27.0,31.0,16.0,8.0,3.0,14.0,25.0,117.0,-9.0

In [310]:
df_away_teams = df_away_teams.reset_index()
df_home_teams = df_home_teams.reset_index()
df_game_data_concat = pd.concat([df_home_teams,df_away_teams], join='inner', axis=1)

In [311]:
df_game_data_concat = df_game_data_concat.drop(columns='GAME_ID')

In [312]:
df_rolling_stats = df_game_data_concat.drop(columns=['SEASON_ID','GAME_DATE','AWAY_TEAM_ID','HOME_TEAM_WINS'])
df_non_rolling_columns = df_game_data_concat[['HOME_TEAM_ID','SEASON_ID','GAME_DATE','AWAY_TEAM_ID','HOME_TEAM_WINS']]
df_rolling_stats.dtypes

HOME_TEAM_ID            float64
HOME_TEAM_MIN           float64
HOME_TEAM_FGM           float64
HOME_TEAM_FGA           float64
HOME_TEAM_FG_PCT        float64
HOME_TEAM_FG3M          float64
HOME_TEAM_FG3A          float64
HOME_TEAM_FG3_PCT       float64
HOME_TEAM_FTM           float64
HOME_TEAM_FTA           float64
HOME_TEAM_FT_PCT        float64
HOME_TEAM_OREB          float64
HOME_TEAM_DREB          float64
HOME_TEAM_REB           float64
HOME_TEAM_AST           float64
HOME_TEAM_STL           float64
HOME_TEAM_BLK           float64
HOME_TEAM_TOV           float64
HOME_TEAM_PF            float64
HOME_TEAM_PTS           float64
HOME_TEAM_PLUS_MINUS    float64
AWAY_TEAM_MIN           float64
AWAY_TEAM_FGM           float64
AWAY_TEAM_FGA           float64
AWAY_TEAM_FG_PCT        float64
AWAY_TEAM_FG3M          float64
AWAY_TEAM_FG3A          float64
AWAY_TEAM_FG3_PCT       float64
AWAY_TEAM_FTM           float64
AWAY_TEAM_FTA           float64
AWAY_TEAM_FT_PCT        float64
AWAY_TEAM_OREB          float64
AWAY_TEAM_DREB          float64
AWAY_TEAM_REB           float64
AWAY_TEAM_AST           float64
AWAY_TEAM_STL           float64
AWAY_TEAM_BLK           float64
AWAY_TEAM_TOV           float64
AWAY_TEAM_PF            float64
AWAY_TEAM_PTS           float64
AWAY_TEAM_PLUS_MINUS    float64
dtype: object

In [313]:
# Shifting all columns down one row 
for column in df_non_rolling_columns:
    df_non_rolling_columns[column] = df_non_rolling_columns[column].shift(periods = 1)

df_non_rolling_columns.dropna(inplace=True)

/Users/Shane/opt/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/Shane/opt/anaconda3/envs/dev/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [314]:
# Shifting all columns down one row 
for column in df_rolling_stats:
    df_rolling_stats[column] = df_rolling_stats[column].shift(periods = 1)

/Users/Shane/opt/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [315]:
# Changing all columns to rolling averages using GroupBy and rolling
df_rolling_stats = df_rolling_stats.groupby(by ='HOME_TEAM_ID', as_index= True).rolling(window = 20).mean()
# Displaying dataframe
display(df_rolling_stats)

                    HOME_TEAM_MIN  HOME_TEAM_FGM  HOME_TEAM_FGA  \
HOME_TEAM_ID
1.610613e+09 17               NaN            NaN            NaN
             41               NaN            NaN            NaN
             92               NaN            NaN            NaN
             114              NaN            NaN            NaN
             125              NaN            NaN            NaN
...                           ...            ...            ...
             70191         241.25          41.10          91.90
             70214         241.25          40.45          92.05
             70245         241.25          40.35          92.10
             70265         242.50          40.55          93.00
             70324         242.50          40.70          93.35

                    HOME_TEAM_FG_PCT  HOME_TEAM_FG3M  HOME_TEAM_FG3A  \
HOME_TEAM_ID
1.610613e+09 17                  NaN             NaN             NaN
             41                  NaN             NaN             NaN
             92                  NaN             NaN             NaN
             114                 NaN             NaN             NaN
             125                 NaN             NaN             NaN
...                              ...             ...             ...
             70191            0.4493           10.30           33.30
             70214            0.4408           10.40           33.75
             70245            0.4393           10.35           33.20
             70265            0.4372           10.50           33.15
             70324            0.4371           10.50           33.30

                    HOME_TEAM_FG3_PCT  HOME_TEAM_FTM  HOME_TEAM_FTA  \
HOME_TEAM_ID
1.610613e+09 17                   NaN            NaN            NaN
             41                   NaN            NaN            NaN
             92                   NaN            NaN            NaN
             114                  NaN            NaN            NaN
             125                  NaN            NaN            NaN
...                               ...            ...            ...
             70191            0.30630          18.30          24.45
             70214            0.30475          18.55          24.45
             70245            0.31015          18.10          24.05
             70265            0.31535          18.00          24.05
             70324            0.31350          17.40          23.25

                    HOME_TEAM_FT_PCT  ...  AWAY_TEAM_OREB  AWAY_TEAM_DREB  \
HOME_TEAM_ID                          ...
1.610613e+09 17                  NaN  ...             NaN             NaN
             41                  NaN  ...             NaN             NaN
             92                  NaN  ...             NaN             NaN
             114                 NaN  ...             NaN             NaN
             125                 NaN  ...             NaN             NaN
...                              ...  ...             ...             ...
             70191           0.74595  ...            9.65           32.00
             70214           0.75685  ...            9.20           31.90
             70245           0.74675  ...            8.80           32.25
             70265           0.74350  ...            8.90           31.70
             70324           0.74445  ...            9.35           31.90

                    AWAY_TEAM_REB  AWAY_TEAM_AST  AWAY_TEAM_STL  \
HOME_TEAM_ID
1.610613e+09 17               NaN            NaN            NaN
             41               NaN            NaN            NaN
             92               NaN            NaN            NaN
             114              NaN            NaN            NaN
             125              NaN            NaN            NaN
...                           ...            ...            ...
             70191          41.65           24.0           7.25
             70214          41.10           23.9           7.35
             70245          41.05           23.9           7.50
             70265          40.60           24.0           7.45
             70324          41.25           24.2           7.50

                    AWAY_TEAM_BLK  AWAY_TEAM_TOV  AWAY_TEAM_PF  AWAY_TEAM_PTS  \
HOME_TEAM_ID
1.610613e+09 17               NaN            NaN           NaN            NaN
             41               NaN            NaN           NaN            NaN
             92               NaN            NaN           NaN            NaN
             114              NaN            NaN           NaN            NaN
             125              NaN            NaN           NaN            NaN
...                           ...            ...           ...            ...
             70191           3.75          13.70         19.60         109.10
             70214           4.15          13.65         19.75         108.05
             70245           4.55          13.65         19.60         107.75
             70265           4.60          13.45         19.85         108.60
             70324           4.65          13.60         19.80         109.85

                    AWAY_TEAM_PLUS_MINUS
HOME_TEAM_ID
1.610613e+09 17                      NaN
             41                      NaN
             92                      NaN
             114                     NaN
             125                     NaN
...                                  ...
             70191                 -4.70
             70214                 -4.80
             70245                 -3.75
             70265                 -3.30
             70324                 -2.55

[70345 rows x 40 columns]

In [316]:
df_rolling_stats = df_rolling_stats.droplevel('HOME_TEAM_ID')
df_rolling_stats

,HOME_TEAM_MIN,HOME_TEAM_FGM,HOME_TEAM_FGA,HOME_TEAM_FG_PCT,HOME_TEAM_FG3M,HOME_TEAM_FG3A,HOME_TEAM_FG3_PCT,HOME_TEAM_FTM,HOME_TEAM_FTA,HOME_TEAM_FT_PCT,...,AWAY_TEAM_OREB,AWAY_TEAM_DREB,AWAY_TEAM_REB,AWAY_TEAM_AST,AWAY_TEAM_STL,AWAY_TEAM_BLK,AWAY_TEAM_TOV,AWAY_TEAM_PF,AWAY_TEAM_PTS,AWAY_TEAM_PLUS_MINUS
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70191,241.25,41.10,91.90,0.4493,10.30,33.30,0.30630,18.30,24.45,0.74595,...,9.65,32.00,41.65,24.0,7.25,3.75,13.70,19.60,109.10,-4.70
70214,241.25,40.45,92.05,0.4408,10.40,33.75,0.30475,18.55,24.45,0.75685,...,9.20,31.90,41.10,23.9,7.35,4.15,13.65,19.75,108.05,-4.80
70245,241.25,40.35,92.10,0.4393,10.35,33.20,0.31015,18.10,24.05,0.74675,...,8.80,32.25,41.05,23.9,7.50,4.55,13.65,19.60,107.75,-3.75
70265,242.50,40.55,93.00,0.4372,10.50,33.15,0.31535,18.00,24.05,0.74350,...,8.90,31.70,40.60,24.0,7.45,4.60,13.45,19.85,108.60,-3.30
70324,242.50,40.70,93.35,0.4371,10.50,33.30,0.31350,17.40,23.25,0.74445,...,9.35,31.90,41.25,24.2,7.50,4.65,13.60,19.80,109.85,-2.55

In [317]:
df_non_rolling_columns.sort_values(by = ['HOME_TEAM_ID'], inplace = True)
df_non_rolling_columns

/Users/Shane/opt/anaconda3/envs/dev/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

,HOME_TEAM_ID,SEASON_ID,SEASON_ID,GAME_DATE,AWAY_TEAM_ID,HOME_TEAM_WINS
6606,1.610613e+09,22006.0,22006.0,2007-01-27,1.610613e+09,0.0
43363,1.610613e+09,22020.0,22020.0,2020-12-28,1.610613e+09,1.0
14466,1.610613e+09,22013.0,22013.0,2014-04-08,1.610613e+09,0.0
68106,1.610613e+09,22020.0,22020.0,2021-01-18,1.610613e+09,1.0
25362,1.610613e+09,22005.0,22005.0,2006-04-18,1.610613e+09,1.0
...,...,...,...,...,...,...
40652,1.610613e+09,22017.0,22017.0,2017-12-18,1.610613e+09,1.0
27930,1.610613e+09,22007.0,22007.0,2008-03-31,1.610613e+09,0.0
40637,1.610613e+09,22017.0,22017.0,2017-12-20,1.610613e+09,0.0
53611,1.610613e+09,22007.0,22007.0,2007-12-12,1.610613e+09,1.0
62079,1.610613e+09,22014.0,22014.0,2014-11-28,1.610613e+09,0.0

In [319]:
df_game_data_final = pd.concat([df_rolling_stats, df_non_rolling_columns], join='inner', axis = 1)

HOME_TEAM_MIN           float64
HOME_TEAM_FGM           float64
HOME_TEAM_FGA           float64
HOME_TEAM_FG_PCT        float64
HOME_TEAM_FG3M          float64
HOME_TEAM_FG3A          float64
HOME_TEAM_FG3_PCT       float64
HOME_TEAM_FTM           float64
HOME_TEAM_FTA           float64
HOME_TEAM_FT_PCT        float64
HOME_TEAM_OREB          float64
HOME_TEAM_DREB          float64
HOME_TEAM_REB           float64
HOME_TEAM_AST           float64
HOME_TEAM_STL           float64
HOME_TEAM_BLK           float64
HOME_TEAM_TOV           float64
HOME_TEAM_PF            float64
HOME_TEAM_PTS           float64
HOME_TEAM_PLUS_MINUS    float64
AWAY_TEAM_MIN           float64
AWAY_TEAM_FGM           float64
AWAY_TEAM_FGA           float64
AWAY_TEAM_FG_PCT        float64
AWAY_TEAM_FG3M          float64
AWAY_TEAM_FG3A          float64
AWAY_TEAM_FG3_PCT       float64
AWAY_TEAM_FTM           float64
AWAY_TEAM_FTA           float64
AWAY_TEAM_FT_PCT        float64
AWAY_TEAM_OREB          float64
AWAY_TEAM_DREB          float64
AWAY_TEAM_REB           float64
AWAY_TEAM_AST           float64
AWAY_TEAM_STL           float64
AWAY_TEAM_BLK           float64
AWAY_TEAM_TOV           float64
AWAY_TEAM_PF            float64
AWAY_TEAM_PTS           float64
AWAY_TEAM_PLUS_MINUS    float64
HOME_TEAM_ID            float64
SEASON_ID               float64
SEASON_ID               float64
GAME_DATE                object
AWAY_TEAM_ID            float64
HOME_TEAM_WINS          float64
dtype: object

In [324]:
df_game_data_final.drop(columns=['SEASON_ID'],inplace=True)

KeyError: "['SEASON_ID'] not found in axis"

In [326]:
# Fixing Data types
df_game_data_final['GAME_DATE'] = pd.to_datetime(df_game_data_final['GAME_DATE'])

In [331]:
df_game_data_final.dropna(inplace=True)
df_game_data_final

,HOME_TEAM_MIN,HOME_TEAM_FGM,HOME_TEAM_FGA,HOME_TEAM_FG_PCT,HOME_TEAM_FG3M,HOME_TEAM_FG3A,HOME_TEAM_FG3_PCT,HOME_TEAM_FTM,HOME_TEAM_FTA,HOME_TEAM_FT_PCT,...,AWAY_TEAM_STL,AWAY_TEAM_BLK,AWAY_TEAM_TOV,AWAY_TEAM_PF,AWAY_TEAM_PTS,AWAY_TEAM_PLUS_MINUS,HOME_TEAM_ID,GAME_DATE,AWAY_TEAM_ID,HOME_TEAM_WINS
562,242.50,38.40,83.75,0.46050,6.55,16.15,0.41765,16.20,21.70,0.74035,...,7.35,4.70,15.85,20.40,96.10,-3.75,1.610613e+09,2002-01-29,1.610613e+09,0.0
584,242.50,38.15,83.60,0.45835,6.50,15.85,0.41825,16.50,21.80,0.74940,...,7.80,5.00,16.30,20.15,95.85,-2.70,1.610613e+09,2002-01-25,1.610613e+09,0.0
614,240.00,37.70,82.15,0.46010,6.25,15.25,0.41615,16.00,21.25,0.74755,...,7.80,5.05,16.40,20.55,96.05,-3.25,1.610613e+09,2002-01-21,1.610613e+09,1.0
624,240.00,38.10,82.20,0.46435,6.40,15.15,0.42590,16.10,21.45,0.74475,...,8.00,5.00,16.55,21.20,95.60,-1.50,1.610613e+09,2002-01-19,1.610613e+09,0.0
643,240.00,38.10,82.70,0.46140,6.35,15.35,0.41900,15.95,21.05,0.75095,...,7.95,5.10,16.55,21.35,95.45,-1.50,1.610613e+09,2002-01-17,1.610613e+09,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70191,241.25,41.10,91.90,0.44930,10.30,33.30,0.30630,18.30,24.45,0.74595,...,7.25,3.75,13.70,19.60,109.10,-4.70,1.610613e+09,2022-11-07,1.610613e+09,0.0
70214,241.25,40.45,92.05,0.44080,10.40,33.75,0.30475,18.55,24.45,0.75685,...,7.35,4.15,13.65,19.75,108.05,-4.80,1.610613e+09,2022-11-05,1.610613e+09,0.0
70245,241.25,40.35,92.10,0.43930,10.35,33.20,0.31015,18.10,24.05,0.74675,...,7.50,4.55,13.65,19.60,107.75,-3.75,1.610613e+09,2022-10-31,1.610613e+09,0.0
70265,242.50,40.55,93.00,0.43720,10.50,33.15,0.31535,18.00,24.05,0.74350,...,7.45,4.60,13.45,19.85,108.60,-3.30,1.610613e+09,2022-10-29,1.610613e+09,1.0
70324,242.50,40.70,93.35,0.43710,10.50,33.30,0.31350,17.40,23.25,0.74445,...,7.50,4.65,13.60,19.80,109.85,-2.55,1.610613e+09,2022-10-21,1.610613e+09,0.0

In [ ]:
df_game_data_final.to_csv('final_data.csv', index=False)